# Generated by Django 2.0.6 on 2020-10-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day08', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pic',
            field=models.ImageField(default='pic/1.jpg', upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.SmallIntegerField(choices=[('0', 'male'), ('1', 'female'), ('2', 'other')], default=0),
        ),
    ]
